#   mm2LaTeX v0.40 Config file
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, version 2.
#


###You'll probably want to change this parameters###

#Pretty self-explanatory
Author='My name'

#Either '\today' or something like '16th February 2002'
Date='\today'

#Abstract included in root node won't be shown unless DocumentType is set to 'article'
DocumentType='article'
DocumentSize='letter'
FontSize='11pt'

#Options used for babel and inputenc
#Windows users may want to change encoding to latin1
Language='english'
Encoding='utf8x'

#List of packages to be used
#if you want to use options, specify package like this:
#'packageName[Option1,Option2,...]'
Packages=[
	'graphicx',
	'ucs',
	'inputenc['+Encoding+']',
	'eurosym',
	'babel['+Language+']',
	'verbatim',
]

#Indent to be used in the LaTeX file structure. By default, [TAB].
Indent="	"

#Structure to be used for a given DocumentType (see above).
LatexStructure={
	'article'	=>
				{0=>'\section',
				1=>'\subsection',
				2=>'\subsubsection',
				3=>'\paragraph'},
				
	'book'		=>
				{0=>'\chapter',
				1=>'\section',
				2=>'\subsection',
				3=>'\subsubsection',
				4=>'\paragraph'}
}


###You'll probably won't have to change this settings###

IntroLaTeX='
\begin{document}
\maketitle'

EndLaTeX='\end{document}

%Automatically generated by mm2latex script
%(http://duminil.info/doku.php?id=freemindtolatex)'

DocumentConfig='\documentclass['+DocumentSize+','+FontSize+']{'+DocumentType+'}'

Figure='
\begin{figure}[!htbp]
\centering
\includegraphics[Options]{ImageName}
\caption{NodeNote}
\end{figure}
'

EnvironmentList={
	/^\[\*\] /=>'itemize',
	/^\[\#\] /=>'enumerate'
}

LatexStructure.each_value{|hash| hash.default=''}

ConvertList={
# <b>bold</b> -> \textbf{bold}
/<b>([^\/]*)<\/b>/=>'\textbf{\1}',
# <i>italic</i> -> \textbf{italic}
/<i>([^\/]*)<\/i>/=>'\textit{\1}',
# <u>underlined</u> -> \underline{underlined}
/<u>([^\/]*)<\/u>/=>'\underline{\1}',
# LaTeX -> \LaTeX
/LaTeX/=>'\LaTeX{}',
# quotation
/"(.*)"/=>'‘‘\1’’',
# single quotation
/'(.*)'/=>'‘\1’',
# Java Comment /*like this*/  -> \begin{comment} like this \end{comment}
/\/\*([^\*\/]*)\*\//=>'\begin{comment} \1 \end{comment}',
# Java Comment //like this -> %like this
/\/\//=>'%',
# ... -> \ldots
/\.\.\./=>'\ldots{}',
# <code>Embedded code</code>
/<code>(.*)<\/code>/m=>'\begin{verbatim} \1 \end{verbatim}',
# €->\euro
/€/=>'\euro{}',
# embedded latex 
/#m\s*([^$].*)/=>'{ \1 }',
/\\#m\s*([^$].*)/=>'{ \1 }',
/#m\s*\$(.*)\$/=>'\begin{equation*} \1 \end{equation*}',
/\\#m\s*\$(.*)\$/=>'\begin{equation*} \1 \end{equation*}',
# #-> \#
/#/=>'\#',
# <image>
/<image>([\w\d\.\/\\]*),?([\w\d\.=,]*)<\/image>/=>
'
\begin{center}
\includegraphics[\2]{\1}
\end{center}
'
}
